[project]
name = "datamall_api_calls_Plentk"
version = "0.0.1"
authors = [
  { name="Plentk", email="plentk.sg@gmail.com" },
]
dependencies = [
  "requests"
]
description = "A package that helps with handling API calls from the Land Transport Authority"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/plentk/LTA-Datamall-Querying"
Issues = "https://github.com/plentk/LTA-Datamall-Querying/issues"
